name: Automation Anypoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  specification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Print Account Information
        run: >
          npm install -g anypoint-cli-v4 &&
          anypoint-cli-v4 account:user:describe --organization_id a7b575c7-b46c-420e-a5ed-5cfd3b43018c --client_id fd689d34075c4d4ca6d5617e4c5ad002 --client_secret 20FBF57bE52e4Da6B596fe2512763541 -o json
        
